version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabitmq
    hostname: rabbitmq
    restart: always
    healthcheck:
        test: rabbitmq-diagnostics -q status && rabbitmq-diagnostics -q check_local_alarms
        interval: 60s
        timeout: 30s
        retries: 3
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASS
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 268435456
    ports:
      - 5672:5672  
      - 15672:15672

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - REDIS_ARGS=--requirepass $REDIS_PASSWORD --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - default
    ports:
      - "6379:6379"

  redis-ui:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on: 
      redis:
        condition: service_healthy
        restart: true

  backend:
    container_name: backend
    build: 
      context: ./event_collector
      dockerfile: backend.Dockerfile
    depends_on: 
      rabbitmq:
        condition: service_healthy
        restart: true
    volumes:
      - ./utils:/app/utils
      - .logs:/app/.logs
    environment:
      - PYTHONPATH=/app/utils
      - RABBITMQ_HOST=$RABBITMQ_HOST
      - RABBITMQ_PORT=$RABBITMQ_PORT
      - RABBITMQ_USER=$RABBITMQ_USER
      - RABBITMQ_PASS=$RABBITMQ_PASS
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports:
      - 5000:5000

  backend-recs:
    container_name: backend-recs
    build: 
      context: ./recommendations
      dockerfile: recs.Dockerfile
    depends_on: 
      rabbitmq:
        condition: service_healthy
        restart: true
    volumes:
      - ./utils:/app/utils
      - .logs:/app/.logs
    environment:
      - PYTHONPATH=/app/utils
      - RABBITMQ_HOST=$RABBITMQ_HOST
      - RABBITMQ_PORT=$RABBITMQ_PORT
      - RABBITMQ_USER=$RABBITMQ_USER
      - RABBITMQ_PASS=$RABBITMQ_PASS
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports:
      - 5001:5001

  frontend:
    container_name: frontend
    build: 
      context: ./webapp
      dockerfile: frontend.Dockerfile
    volumes:
      - ./utils:/app/utils
    environment:
      - PYTHONPATH=/app/utils
      - RECSYS_SERVICE_URL=$RECSYS_SERVICE_URL
      - SERVICE_API_URL=$SERVICE_API_URL
      - S3_PUB=$S3_PUB
      - S3_SECRET=$S3_SECRET
    ports:
      - 8000:8000

  ml-pipeline:
    container_name: ml-pipeline
    build: 
      context: ./regular_pipeline
      dockerfile: ml-pipeline.Dockerfile
    depends_on: 
      rabbitmq:
        condition: service_healthy
        restart: true
    volumes:
      - ./utils:/app/utils
      - ./data:/app/data
      - .logs:/app/.logs
    environment:
      - PYTHONPATH=/app/utils
      - RABBITMQ_HOST=$RABBITMQ_HOST
      - RABBITMQ_PORT=$RABBITMQ_PORT
      - RABBITMQ_USER=$RABBITMQ_USER
      - RABBITMQ_PASS=$RABBITMQ_PASS
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD